# Use Python 3.12 as base image
FROM python:3.12-slim

# Set working directory

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN pip install --upgrade pip
COPY ../requirements.txt .
RUN pip install -r requirements.txt

# Copy application code
COPY .. .

# Expose Streamlit port
EXPOSE 8501

# Run Streamlit app
CMD ["uv", "run", "streamlit", "run", "landuse_app.py", "--server.port=8501", "--server.address=0.0.0.0"] 