# Schema Definition v2.2.0
# Current production schema for RPA Land Use Analytics
version: 2.2.0
description: "Combined scenarios with statistical fields and versioning system"
author: "system"
created_at: "2025-01-01T00:00:00Z"
backward_compatible: true

tables:
  dim_scenario:
    description: "Climate scenario dimension table with combined RCP-SSP scenarios"
    ddl: |
      CREATE TABLE IF NOT EXISTS dim_scenario (
        scenario_id INTEGER PRIMARY KEY,
        scenario_name VARCHAR(100) NOT NULL,
        rcp_scenario VARCHAR(20),
        ssp_scenario VARCHAR(20),
        description TEXT,
        narrative TEXT,
        aggregation_method VARCHAR(50) DEFAULT 'mean',
        gcm_count INTEGER DEFAULT 5,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    indexes:
      - CREATE INDEX IF NOT EXISTS idx_scenario_name ON dim_scenario(scenario_name)
    constraints:
      - type: UNIQUE
        columns: [scenario_name]

  dim_time:
    description: "Time dimension table for temporal analysis"
    ddl: |
      CREATE TABLE IF NOT EXISTS dim_time (
        time_id INTEGER PRIMARY KEY,
        year_range VARCHAR(20) NOT NULL,
        start_year INTEGER,
        end_year INTEGER,
        period_length INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    indexes:
      - CREATE INDEX IF NOT EXISTS idx_time_range ON dim_time(year_range)

  dim_geography:
    description: "Geography dimension table for US counties"
    ddl: |
      CREATE TABLE IF NOT EXISTS dim_geography (
        geography_id INTEGER PRIMARY KEY,
        fips_code VARCHAR(10) NOT NULL UNIQUE,
        county_name VARCHAR(100),
        state_code VARCHAR(2),
        state_name VARCHAR(50),
        region VARCHAR(50),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    indexes:
      - CREATE INDEX IF NOT EXISTS idx_geography_fips ON dim_geography(fips_code)
      - CREATE INDEX IF NOT EXISTS idx_geography_state ON dim_geography(state_code)

  dim_landuse:
    description: "Land use type dimension table"
    ddl: |
      CREATE TABLE IF NOT EXISTS dim_landuse (
        landuse_id INTEGER PRIMARY KEY,
        landuse_code VARCHAR(10) NOT NULL UNIQUE,
        landuse_name VARCHAR(50) NOT NULL,
        landuse_category VARCHAR(30),
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    indexes:
      - CREATE INDEX IF NOT EXISTS idx_landuse_code ON dim_landuse(landuse_code)

  fact_landuse_transitions:
    description: "Main fact table for land use transitions with aggregated metrics"
    ddl: |
      CREATE TABLE IF NOT EXISTS fact_landuse_transitions (
        transition_id BIGINT PRIMARY KEY,
        scenario_id INTEGER NOT NULL,
        time_id INTEGER NOT NULL,
        geography_id INTEGER NOT NULL,
        from_landuse_id INTEGER NOT NULL,
        to_landuse_id INTEGER NOT NULL,
        acres DECIMAL(15,4) NOT NULL,
        acres_std_dev DECIMAL(15,4),
        acres_min DECIMAL(15,4),
        acres_max DECIMAL(15,4),
        transition_type VARCHAR(20) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (scenario_id) REFERENCES dim_scenario(scenario_id),
        FOREIGN KEY (time_id) REFERENCES dim_time(time_id),
        FOREIGN KEY (geography_id) REFERENCES dim_geography(geography_id),
        FOREIGN KEY (from_landuse_id) REFERENCES dim_landuse(landuse_id),
        FOREIGN KEY (to_landuse_id) REFERENCES dim_landuse(landuse_id)
      )
    indexes:
      - CREATE INDEX IF NOT EXISTS idx_fact_scenario ON fact_landuse_transitions(scenario_id)
      - CREATE INDEX IF NOT EXISTS idx_fact_time ON fact_landuse_transitions(time_id)
      - CREATE INDEX IF NOT EXISTS idx_fact_geography ON fact_landuse_transitions(geography_id)
      - CREATE INDEX IF NOT EXISTS idx_fact_from_landuse ON fact_landuse_transitions(from_landuse_id)
      - CREATE INDEX IF NOT EXISTS idx_fact_to_landuse ON fact_landuse_transitions(to_landuse_id)
      - CREATE INDEX IF NOT EXISTS idx_fact_composite ON fact_landuse_transitions(scenario_id, time_id, geography_id)
    partitioning:
      type: "range"
      column: "time_id"
      description: "Partitioned by time periods for query performance"

  schema_version:
    description: "Schema versioning table for tracking database evolution"
    ddl: |
      CREATE TABLE IF NOT EXISTS schema_version (
        version_id INTEGER PRIMARY KEY,
        version_number VARCHAR(20) NOT NULL,
        description TEXT,
        applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        applied_by VARCHAR(100),
        UNIQUE(version_number)
      )

views:
  v_default_transitions:
    description: "Default view for OVERALL scenario transitions"
    ddl: |
      CREATE OR REPLACE VIEW v_default_transitions AS
      SELECT
        f.*,
        s.scenario_name,
        s.rcp_scenario,
        s.ssp_scenario,
        t.year_range,
        t.start_year,
        t.end_year,
        g.fips_code,
        g.county_name,
        g.state_name,
        g.region,
        fl.landuse_name as from_landuse,
        tl.landuse_name as to_landuse
      FROM fact_landuse_transitions f
      JOIN dim_scenario s ON f.scenario_id = s.scenario_id
      JOIN dim_time t ON f.time_id = t.time_id
      JOIN dim_geography g ON f.geography_id = g.geography_id
      JOIN dim_landuse fl ON f.from_landuse_id = fl.landuse_id
      JOIN dim_landuse tl ON f.to_landuse_id = tl.landuse_id
      WHERE s.scenario_name = 'OVERALL'

  v_scenario_comparisons:
    description: "View for comparing scenarios side by side"
    ddl: |
      CREATE OR REPLACE VIEW v_scenario_comparisons AS
      SELECT
        s.scenario_name,
        s.rcp_scenario,
        s.ssp_scenario,
        t.year_range,
        g.state_name,
        fl.landuse_name as from_landuse,
        tl.landuse_name as to_landuse,
        SUM(f.acres) as total_acres,
        AVG(f.acres_std_dev) as avg_std_dev,
        COUNT(*) as transition_count
      FROM fact_landuse_transitions f
      JOIN dim_scenario s ON f.scenario_id = s.scenario_id
      JOIN dim_time t ON f.time_id = t.time_id
      JOIN dim_geography g ON f.geography_id = g.geography_id
      JOIN dim_landuse fl ON f.from_landuse_id = fl.landuse_id
      JOIN dim_landuse tl ON f.to_landuse_id = tl.landuse_id
      WHERE s.scenario_name != 'OVERALL'
      GROUP BY
        s.scenario_name,
        s.rcp_scenario,
        s.ssp_scenario,
        t.year_range,
        g.state_name,
        fl.landuse_name,
        tl.landuse_name