name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Streamlit Dashboard
        - Natural Language Agent
        - Database Connection
        - Data Conversion
        - Bulk Loading
        - Documentation
        - Tests
        - Other
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: ex. v1.0.0 or commit hash
    validations:
      required: true
      
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      options:
        - "3.11"
        - "3.12"
        - "3.13"
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - uv version: 
        - Database size:
        - Memory available:
        - Any relevant configuration:
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error messages, related issues, etc.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true