name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Streamlit Dashboard
        - Natural Language Agent
        - Database Connection
        - Data Conversion
        - Bulk Loading
        - API/Integration
        - Documentation
        - Tests
        - CLI Tools
        - Performance
        - Security
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        - What are you trying to accomplish?
        - How would this feature help?
        - What is your current workaround (if any)?
    validations:
      required: true
      
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas on how this could be implemented?
      placeholder: |
        - Technical approach suggestions
        - API design ideas
        - UI/UX considerations
        - Any relevant examples or references
    validations:
      required: false
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide domain expertise/requirements
          
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: |
        - Links to similar features in other tools
        - Screenshots or mockups
        - Related issues or discussions
        - Business justification
    validations:
      required: false