services:
  streamlit-app:
    image: 810875545305.dkr.ecr.us-east-1.amazonaws.com/rpa-landuse:streamlit-latest
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile.yml
    command: >
      streamlit run landuse_app.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.headless=true
      --server.enableCORS=false
      --server.enableXsrfProtection=true
      --server.maxUploadSize=200
      --logger.level=info
    ports:
      - "80:8501"
    env_file:
      - ./.env.dev
    volumes:
      # Mount only necessary files/directories for faster performance
      - ../../landuse_app.py:/app/landuse_app.py
      - ../../src:/app/src
      - ../../views:/app/views
      - ../../data:/app/data
